### ISSUE TITLE
List all pages in the system along with its statistics

### ISSUE THREAD

**Issue by safwan-samsudeen** [ssamsudeen/quran_srs#5]
After I enter the revision, there is no way for me to see the status of all the pages that are in the system, except when they are due.

**Comment by ssamsudeen** [comment]
Also, added the functionality to see the revisions of a page from "all_pages"

**Comment by ssamsudeen** [comment]
<img width="1008" alt="Screenshot 2020-03-20 at 7 30 54 PM" src="https://user-images.githubusercontent.com/11910293/77170646-584f4f80-6ae1-11ea-999a-4cb0cc152fde.png">
